const destinations=[
{id:1,name:"Goa",state:"Goa",region:"West",rating:4.8,budget:"₹8,000 – ₹20,000",bestTime:"October – March",categories:["Beach","Family","Couple"],image:"https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80",description:"Golden beaches, Portuguese heritage, vibrant nightlife and laid-back coastal vibes make Goa one of India's favorite escapes.",attractions:["Baga Beach","Calangute Beach","Fort Aguada","Basilica of Bom Jesus"]},
{id:2,name:"Manali",state:"Himachal Pradesh",region:"North",rating:4.7,budget:"₹7,000 – ₹18,000",bestTime:"October – June",categories:["Adventure","Family"],image:"https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80",description:"A beautiful Himalayan getaway filled with mountain views, snow, adventure activities and peaceful valleys.",attractions:["Solang Valley","Rohtang Pass","Hadimba Temple","Old Manali"]},
{id:3,name:"Jaipur",state:"Rajasthan",region:"North",rating:4.6,budget:"₹6,000 – ₹15,000",bestTime:"October – March",categories:["Historical","Family"],image:"https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80",description:"The Pink City is a colorful mix of royal palaces, grand forts, local markets and Rajasthani culture.",attractions:["Amber Fort","Hawa Mahal","City Palace","Jantar Mantar"]},
{id:4,name:"Kerala",state:"Kerala",region:"South",rating:4.9,budget:"₹9,000 – ₹22,000",bestTime:"September – March",categories:["Family","Couple"],image:"https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80",description:"Experience tranquil backwaters, lush hills, beaches and incredible food in God's Own Country.",attractions:["Alleppey","Munnar","Kovalam","Thekkady"]},
{id:5,name:"Ladakh",state:"Ladakh",region:"North",rating:4.8,budget:"₹15,000 – ₹35,000",bestTime:"May – September",categories:["Adventure"],image:"https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80",description:"High-altitude deserts, dramatic mountains, monasteries and turquoise lakes make Ladakh unforgettable.",attractions:["Pangong Lake","Nubra Valley","Leh Palace","Shanti Stupa"]},
{id:6,name:"Mumbai",state:"Maharashtra",region:"West",rating:4.5,budget:"₹5,000 – ₹15,000",bestTime:"October – February",categories:["Family","Historical"],image:"https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=1200&q=80",description:"India's energetic financial capital blends colonial heritage, street food, beaches, art and entertainment.",attractions:["Gateway of India","Marine Drive","Elephanta Caves","Colaba"]},
{id:7,name:"Andaman",state:"Andaman & Nicobar",region:"East",rating:4.8,budget:"₹18,000 – ₹40,000",bestTime:"October – May",categories:["Beach","Couple"],image:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",description:"Crystal-clear waters, coral reefs and quiet island beaches create a perfect tropical getaway.",attractions:["Radhanagar Beach","Cellular Jail","Elephant Beach","Ross Island"]},
{id:8,name:"Sikkim",state:"Sikkim",region:"Northeast",rating:4.7,budget:"₹10,000 – ₹24,000",bestTime:"March – June",categories:["Adventure","Family"],image:"https://images.unsplash.com/photo-1518002054494-3a6f94352e9d?auto=format&fit=crop&w=1200&q=80",description:"Peaceful monasteries, mountain landscapes and vibrant local culture in the Eastern Himalayas.",attractions:["Gangtok","Tsomgo Lake","Nathula Pass","Pelling"]}
];

const extraDestinations=[
{id:9,name:"Varanasi",state:"Uttar Pradesh",region:"North",rating:4.9,budget:"₹6,000 – ₹16,000",bestTime:"October – March",categories:["Historical","Family","Couple"],image:"https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80",description:"One of India's oldest living cities, famous for the Ganges ghats, spiritual traditions and vibrant old-city lanes.",attractions:["Dashashwamedh Ghat","Kashi Vishwanath Temple","Assi Ghat","Sarnath"]},
{id:10,name:"Udaipur",state:"Rajasthan",region:"West",rating:4.8,budget:"₹7,000 – ₹18,000",bestTime:"October – March",categories:["Historical","Couple","Family"],image:"https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80",description:"A romantic city of lakes, palaces and royal heritage in Rajasthan.",attractions:["Lake Pichola","City Palace","Jag Mandir","Saheliyon Ki Bari"]},
{id:11,name:"Rishikesh",state:"Uttarakhand",region:"North",rating:4.8,budget:"₹5,000 – ₹14,000",bestTime:"September – June",categories:["Adventure","Family"],image:"https://images.unsplash.com/photo-1595815771614-ade9d1c2a3f5?auto=format&fit=crop&w=1200&q=80",description:"A Himalayan gateway known for yoga, river rafting, temples and scenic river views.",attractions:["Laxman Jhula","Triveni Ghat","River Rafting","Neer Garh Waterfall"]},
{id:12,name:"Agra",state:"Uttar Pradesh",region:"North",rating:4.7,budget:"₹4,000 – ₹12,000",bestTime:"October – March",categories:["Historical","Family"],image:"https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=80",description:"Home of the Taj Mahal and a major destination for India's Mughal heritage.",attractions:["Taj Mahal","Agra Fort","Mehtab Bagh","Itmad-ud-Daulah"]},
{id:13,name:"Amritsar",state:"Punjab",region:"North",rating:4.7,budget:"₹4,500 – ₹13,000",bestTime:"October – March",categories:["Historical","Family"],image:"https://images.unsplash.com/photo-1588096344356-3f5c8b6f1f67?auto=format&fit=crop&w=1200&q=80",description:"A cultural and spiritual destination famous for the Golden Temple and Punjabi hospitality.",attractions:["Golden Temple","Jallianwala Bagh","Wagah Border","Partition Museum"]},
{id:14,name:"Ayodhya",state:"Uttar Pradesh",region:"North",rating:4.7,budget:"₹4,000 – ₹12,000",bestTime:"October – March",categories:["Historical","Family"],image:"https://images.unsplash.com/photo-1605640840605-14ac1855827b?auto=format&fit=crop&w=1200&q=80",description:"A historic city on the Sarayu River with temples, ghats and rich cultural heritage.",attractions:["Ram Mandir","Saryu Ghat","Hanuman Garhi","Kanak Bhawan"]},
{id:15,name:"Hampi",state:"Karnataka",region:"South",rating:4.8,budget:"₹5,000 – ₹14,000",bestTime:"October – February",categories:["Historical","Adventure"],image:"https://images.unsplash.com/photo-1600100397608-f010e1d9f4e7?auto=format&fit=crop&w=1200&q=80",description:"Ancient ruins, giant boulders and temples create one of India's most memorable heritage landscapes.",attractions:["Virupaksha Temple","Vittala Temple","Hampi Bazaar","Matanga Hill"]},
{id:16,name:"Mysore",state:"Karnataka",region:"South",rating:4.6,budget:"₹5,000 – ₹14,000",bestTime:"October – February",categories:["Historical","Family"],image:"https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=1200&q=80",description:"A royal Karnataka city known for its palace, markets, culture and cuisine.",attractions:["Mysore Palace","Chamundi Hill","Brindavan Gardens","Devaraja Market"]},
{id:17,name:"Ooty",state:"Tamil Nadu",region:"South",rating:4.6,budget:"₹6,000 – ₹15,000",bestTime:"October – June",categories:["Family","Couple"],image:"https://images.unsplash.com/photo-1593693411515-c20261bcad6e?auto=format&fit=crop&w=1200&q=80",description:"A cool Nilgiri hill station with tea gardens, lakes and scenic mountain railways.",attractions:["Ooty Lake","Botanical Garden","Doddabetta Peak","Nilgiri Mountain Railway"]},
{id:18,name:"Darjeeling",state:"West Bengal",region:"Northeast",rating:4.7,budget:"₹7,000 – ₹18,000",bestTime:"March – May",categories:["Adventure","Family"],image:"https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",description:"Tea estates, Himalayan views and the famous toy train make Darjeeling a classic hill escape.",attractions:["Tiger Hill","Batasia Loop","Darjeeling Himalayan Railway","Tea Gardens"]},
{id:19,name:"Kolkata",state:"West Bengal",region:"East",rating:4.5,budget:"₹4,000 – ₹12,000",bestTime:"October – March",categories:["Historical","Family"],image:"https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=1200&q=80",description:"A vibrant cultural capital filled with colonial architecture, art, food and literature.",attractions:["Victoria Memorial","Howrah Bridge","Indian Museum","Park Street"]},
{id:20,name:"Pune",state:"Maharashtra",region:"West",rating:4.5,budget:"₹4,000 – ₹11,000",bestTime:"October – February",categories:["Historical","Family"],image:"https://images.unsplash.com/photo-1595658658481-d53d3f999875?auto=format&fit=crop&w=1200&q=80",description:"A lively city combining history, education, food culture and nearby hill getaways.",attractions:["Shaniwar Wada","Aga Khan Palace","Sinhagad Fort","Pataleshwar Cave Temple"]},
{id:21,name:"Nashik",state:"Maharashtra",region:"West",rating:4.5,budget:"₹4,000 – ₹11,000",bestTime:"October – February",categories:["Historical","Family"],image:"https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=80",description:"A riverside pilgrimage and wine-region destination with temples, vineyards and scenic surroundings.",attractions:["Trimbakeshwar","Sula Vineyards","Panchavati","Godavari Ghats"]},
{id:22,name:"Coorg",state:"Karnataka",region:"South",rating:4.7,budget:"₹6,000 – ₹16,000",bestTime:"October – March",categories:["Adventure","Couple","Family"],image:"https://images.unsplash.com/photo-1586613837154-5a1b1f6a4d9c?auto=format&fit=crop&w=1200&q=80",description:"Misty hills, coffee plantations and waterfalls make Coorg a peaceful nature escape.",attractions:["Abbey Falls","Raja's Seat","Dubare","Coffee Plantations"]},
{id:23,name:"Pondicherry",state:"Puducherry",region:"South",rating:4.6,budget:"₹5,000 – ₹14,000",bestTime:"October – March",categories:["Beach","Couple","Family"],image:"https://images.unsplash.com/photo-1609947017136-9daf32a5eb16?auto=format&fit=crop&w=1200&q=80",description:"French-inspired streets, beaches, cafes and a relaxed coastal atmosphere.",attractions:["Promenade Beach","White Town","Auroville","Paradise Beach"]},
{id:24,name:"Jaisalmer",state:"Rajasthan",region:"West",rating:4.7,budget:"₹7,000 – ₹17,000",bestTime:"October – February",categories:["Historical","Adventure"],image:"https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80",description:"The Golden City is known for its sandstone fort, desert camps and camel safaris.",attractions:["Jaisalmer Fort","Sam Sand Dunes","Patwon Ki Haveli","Gadisar Lake"]},
{id:25,name:"Shimla",state:"Himachal Pradesh",region:"North",rating:4.6,budget:"₹6,000 – ₹16,000",bestTime:"March – June",categories:["Family","Couple"],image:"https://images.unsplash.com/photo-1597074866923-dc0589150358?auto=format&fit=crop&w=1200&q=80",description:"A classic Himalayan hill station with colonial architecture, forests and mountain views.",attractions:["Mall Road","The Ridge","Jakhu Temple","Kufri"]},
{id:26,name:"Mussoorie",state:"Uttarakhand",region:"North",rating:4.6,budget:"₹6,000 – ₹15,000",bestTime:"March – June",categories:["Family","Couple"],image:"https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80",description:"The Queen of the Hills offers waterfalls, viewpoints and a charming mountain-town experience.",attractions:["Mall Road","Kempty Falls","Gun Hill","Lal Tibba"]}
];
destinations.push(...extraDestinations);

const packages=[
{id:101,name:"Goa Explorer",destination:"Goa",duration:"5 Days / 4 Nights",price:15999,image:destinations[0].image,description:"Beaches, sightseeing, local food and relaxing coastal experiences.",includes:["Hotel","Breakfast","Sightseeing","Airport pickup"],itinerary:[["Day 1","Arrival & check-in","Relax and explore the nearby beach."],["Day 2","North Goa","Baga, Calangute and Fort Aguada."],["Day 3","South Goa","Explore churches, beaches and local markets."],["Day 4","Leisure Day","Optional water sports and sunset cruise."],["Day 5","Departure","Breakfast and checkout."]]},
{id:102,name:"Manali Adventure",destination:"Manali",duration:"5 Days / 4 Nights",price:18999,image:destinations[1].image,description:"Mountain sightseeing with adventure activities and cozy stays.",includes:["Hotel","Breakfast","Cab","Sightseeing"],itinerary:[["Day 1","Arrival","Check-in and local market visit."],["Day 2","Solang Valley","Adventure activities and mountain views."],["Day 3","Rohtang Region","Snow and scenic mountain drive."],["Day 4","Old Manali","Temple, cafes and leisure."],["Day 5","Departure","Checkout and return."]]},
{id:103,name:"Kerala Escape",destination:"Kerala",duration:"6 Days / 5 Nights",price:22500,image:destinations[3].image,description:"Backwaters, hills, beaches and authentic Kerala experiences.",includes:["Hotel","Breakfast","Houseboat","Transfers"],itinerary:[["Day 1","Kochi","Arrival and heritage sightseeing."],["Day 2","Munnar","Scenic drive and tea gardens."],["Day 3","Munnar","Waterfalls and viewpoints."],["Day 4","Alleppey","Houseboat check-in."],["Day 5","Kovalam","Beach and leisure."],["Day 6","Departure","Checkout and airport transfer."]]},
{id:104,name:"Jaipur Heritage",destination:"Jaipur",duration:"4 Days / 3 Nights",price:12500,image:destinations[2].image,description:"Royal forts, palaces, markets and local Rajasthani culture.",includes:["Hotel","Breakfast","Guide","Local transfers"],itinerary:[["Day 1","Pink City","City Palace and local market."],["Day 2","Amber Fort","Amber, Jal Mahal and Hawa Mahal."],["Day 3","Culture","Jantar Mantar and craft shopping."],["Day 4","Departure","Breakfast and checkout."]]}
];
const hotels=[
{name:"Goa Grand Resort",city:"Goa",type:"Luxury",rating:4.7,price:4500,image:destinations[0].image,facilities:["WiFi","Pool","Breakfast","Parking"]},
{name:"Manali Mountain Stay",city:"Manali",type:"Family",rating:4.6,price:3200,image:destinations[1].image,facilities:["WiFi","Breakfast","Parking","Mountain View"]},
{name:"Pink City Palace Hotel",city:"Jaipur",type:"Luxury",rating:4.5,price:3800,image:destinations[2].image,facilities:["WiFi","Pool","Restaurant","Parking"]},
{name:"Kerala Backwater Retreat",city:"Kerala",type:"Couple",rating:4.9,price:5200,image:destinations[3].image,facilities:["WiFi","Houseboat","Breakfast","Spa"]},
{name:"Ladakh View Camp",city:"Ladakh",type:"Budget",rating:4.6,price:2400,image:destinations[4].image,facilities:["WiFi","Meals","Parking","Mountain View"]},
{name:"Mumbai Central Hotel",city:"Mumbai",type:"Budget",rating:4.4,price:2900,image:destinations[5].image,facilities:["WiFi","Breakfast","Parking","Restaurant"]}
];
const reviews=[["Priya Sharma",5,"Beautiful beaches and a very relaxing trip. Goa was amazing!"],["Arjun Mehta",5,"The mountain views were unforgettable. Manali is a must visit."],["Neha Patil",5,"Loved the backwaters and food. Kerala exceeded expectations."],["Rohit Verma",4,"Great heritage experience and delicious local food in Jaipur."]];
